// @generated by tools/gen_http_route_manifest_from_openapi.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest, RateLimitTier};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::ingress_token(
        HttpMethod::Post,
        "/internal/v3/api/knowledgebase/drive_events",
        "knowledgebase",
        "driveEvents.receive",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/knowledgebase/wiki_publications/{publicationUuid}",
        "knowledgebase",
        "wikiPublications.retrieve",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/knowledgebase/wiki_publications/{publicationUuid}/contents/{contentHandle}",
        "knowledgebase",
        "wikiPublications.contents.retrieve",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/knowledgebase/wiki_publications/{publicationUuid}/navigation",
        "knowledgebase",
        "wikiPublications.navigation.list",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/knowledgebase/wiki_publications/{publicationUuid}/pages/search",
        "knowledgebase",
        "wikiPublications.pages.search",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
    HttpRoute::ingress_token(
        HttpMethod::Post,
        "/internal/v3/api/knowledgebase/wiki_publications/{publicationUuid}/routes/resolve",
        "knowledgebase",
        "wikiPublications.routes.resolve",
    )
    .with_rate_limit_tier(
        RateLimitTier::Internal,
    ),
];

pub fn internal_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
