//! Generated gateway bootstrap for sdkwork-knowledgebase.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_knowledgebase_app_api::gateway_mount(browser));
    router = router.merge(sdkwork_routes_knowledgebase_backend_api::gateway_mount(api, runtime_tenant_id));
    router = router.merge(sdkwork_routes_knowledgebase_open_api::gateway_mount(api));
    ApplicationAssembly { router }
}
