use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/sources",
        "knowledge",
        "sources.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/sources",
        "knowledge",
        "sources.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_compile_jobs",
        "knowledge",
        "wiki.compileJobs.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/wiki_candidates",
        "knowledge",
        "wiki.candidates.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_candidates/{candidateId}/approve",
        "knowledge",
        "wiki.candidates.approve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_candidates/{candidateId}/reject",
        "knowledge",
        "wiki.candidates.reject",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_pages/{pageId}/publish",
        "knowledge",
        "wiki.pages.publish",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_schema_profiles",
        "knowledge",
        "wiki.schema.profiles.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/knowledge/wiki_schema_profiles/{profileId}",
        "knowledge",
        "wiki.schema.profiles.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_index/rebuild",
        "knowledge",
        "wiki.index.rebuild",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_log_entries",
        "knowledge",
        "wiki.log.entries.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_exports",
        "knowledge",
        "wiki.exports.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/wiki_exports/{exportId}",
        "knowledge",
        "wiki.exports.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/wiki_file_entries",
        "knowledge",
        "wiki.fileEntries.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_lint_runs",
        "knowledge",
        "wiki.lintRuns.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/wiki_eval_runs",
        "knowledge",
        "wiki.evalRuns.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/indexes",
        "knowledge",
        "indexes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/indexes/{indexId}",
        "knowledge",
        "indexes.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/indexes/{indexId}/rebuild",
        "knowledge",
        "indexes.rebuild",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/retrieval_profiles",
        "knowledge",
        "retrievalProfiles.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_profiles/{profileId}",
        "knowledge",
        "retrievalProfiles.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/knowledge/retrieval_profiles/{profileId}",
        "knowledge",
        "retrievalProfiles.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_traces",
        "knowledge",
        "retrievalTraces.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_traces/{traceId}",
        "knowledge",
        "retrievalTraces.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/provider_health",
        "knowledge",
        "providerHealth.retrieve",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
