use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest, RateLimitTier};

const fn abuse_sensitive_route(
    method: HttpMethod,
    path: &'static str,
    tag: &'static str,
    operation_id: &'static str,
) -> HttpRoute {
    HttpRoute::dual_token(method, path, tag, operation_id)
        .with_rate_limit_tier(RateLimitTier::AuthCritical)
}

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/sources",
        "knowledge",
        "sources.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/sources",
        "knowledge",
        "sources.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/compile_jobs",
        "knowledge",
        "okf.compileJobs.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/okf/candidates",
        "knowledge",
        "okf.candidates.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/candidates/{candidateId}/approve",
        "knowledge",
        "okf.candidates.approve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/candidates/{candidateId}/reject",
        "knowledge",
        "okf.candidates.reject",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/concepts/{conceptId}/publish",
        "knowledge",
        "okf.concepts.publish",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/profile",
        "knowledge",
        "okf.profile.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/knowledge/okf/profile/{profileId}",
        "knowledge",
        "okf.profile.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/index/rebuild",
        "knowledge",
        "okf.bundle.index.rebuild",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/log_entries",
        "knowledge",
        "okf.log.entries.create",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/exports",
        "knowledge",
        "okf.bundle.export.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/okf/exports/{exportId}",
        "knowledge",
        "okf.bundle.export.retrieve",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/imports",
        "knowledge",
        "okf.bundle.import.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/okf/bundle/files",
        "knowledge",
        "okf.bundle.files.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/lint_runs",
        "knowledge",
        "okf.lintRuns.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/okf/eval_runs",
        "knowledge",
        "okf.evalRuns.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/indexes",
        "knowledge",
        "indexes.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/indexes",
        "knowledge",
        "indexes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/indexes/{indexId}",
        "knowledge",
        "indexes.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/indexes/{indexId}/rebuild",
        "knowledge",
        "indexes.rebuild",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/retrieval_profiles",
        "knowledge",
        "retrievalProfiles.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_profiles/{profileId}",
        "knowledge",
        "retrievalProfiles.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/knowledge/retrieval_profiles/{profileId}",
        "knowledge",
        "retrievalProfiles.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_traces",
        "knowledge",
        "retrievalTraces.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/retrieval_traces/{traceId}",
        "knowledge",
        "retrievalTraces.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/provider_health",
        "knowledge",
        "providerHealth.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/provider_credential_references",
        "knowledge",
        "providerCredentialReferences.list",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/provider_credential_references",
        "knowledge",
        "providerCredentialReferences.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/provider_credential_references/{credentialReferenceId}",
        "knowledge",
        "providerCredentialReferences.retrieve",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/provider_credential_references/{credentialReferenceId}/rotate",
        "knowledge",
        "providerCredentialReferences.rotate",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/provider_credential_references/{credentialReferenceId}/revoke",
        "knowledge",
        "providerCredentialReferences.revoke",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings",
        "knowledge",
        "spaces.providerBindings.list",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings",
        "knowledge",
        "spaces.providerBindings.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings/{bindingId}",
        "knowledge",
        "spaces.providerBindings.retrieve",
    ),
    abuse_sensitive_route(
        HttpMethod::Patch,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings/{bindingId}",
        "knowledge",
        "spaces.providerBindings.update",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings/{bindingId}/test",
        "knowledge",
        "spaces.providerBindings.test",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings/{bindingId}/activate",
        "knowledge",
        "spaces.providerBindings.activate",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_bindings/{bindingId}/disable",
        "knowledge",
        "spaces.providerBindings.disable",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_migrations",
        "knowledge",
        "spaces.providerMigrations.list",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_migrations",
        "knowledge",
        "spaces.providerMigrations.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_migrations/{migrationOperationId}",
        "knowledge",
        "spaces.providerMigrations.retrieve",
    ),
    abuse_sensitive_route(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/spaces/{spaceId}/provider_migrations/{migrationOperationId}/rollback",
        "knowledge",
        "spaces.providerMigrations.rollback",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/group_launch_capability",
        "knowledge",
        "groupLaunchCapability.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/tenants/current",
        "knowledge",
        "tenants.current.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces",
        "knowledge",
        "spaces.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/knowledge/spaces/{spaceId}/members",
        "knowledge",
        "spaces.members.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/compliance/audit_events/export",
        "knowledge",
        "compliance.auditEvents.export.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/knowledge/compliance/audit_events/anonymize_actor",
        "knowledge",
        "compliance.auditEvents.anonymizeActor.create",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
