const fs = require('fs');

const zhFile = './src/i18n/locales/zh/kb.json';
const zhData = JSON.parse(fs.readFileSync(zhFile, 'utf8'));
Object.assign(zhData, {
  "basicSettings": "基础配置",
  "permissionsSettings": "权限管理",
  "modelSettings": "智脑模型设置",
  "basicSettingsDesc": "修改基本名称、外观、图标、知识库的分类范围。",
  "permissionsSettingsDesc": "访问权限 & 外部共享设置",
  "permissionsSettingsDesc2": "设置知识库组织成员协作职责，管理Public公开链路访问规则。",
  "modelSettingsDesc": "大语言模型智能体控制台",
  "modelSettingsDesc2": "设置该知识库关联的 AI 理解驱动引擎参数及上下文智能指示。",
  "kbSpace": "知识库空间",
  "kbRename": "知识库重命名",
  "kbRenamePlaceholder": "例如：产品架构规范书...",
  "iconAvatarSelection": "挑选图标或上传头像",
  "recommendedSize": "支持拖拽上传图片。建议 512x512px，JPG/PNG。",
  "admin": "管理员 (Admin)",
  "editor": "编辑者 (Editor)",
  "viewer": "只读游客 (Viewer)",
  "collaborators": "内部协作成员",
  "addCollaborator": "添加协作者邮箱，共同维护此知识库",
  "emailPlaceholder": "输入团队成员邮箱 (如: name@company.com)",
  "add": "添加",
  "owner": "所有者",
  "removeMember": "移除成员",
  "cloudProvider": "云算力主要提供商 (AI Provider)",
  "llmModel": "关联 LLM 大语言模型执行器",
  "temperature": "创意随机温度 (Temperature)",
  "temperatureDesc": "较低的数值产生更加确定性、准确的事实性回复；较高的数值会获得多样性、极具创意的扩散性回答，适合头脑风暴。",
  "maxTokens": "输出单词上限 (Max Output Tokens)",
  "maxTokensDesc": "配置生成引擎单词Token上限，约束大规模文本截断。",
  "systemPrompt": "设定专属系统提示词身份 (System Prompt)",
  "systemPromptPlaceholder": "输入身份预设，比如：你现在是金融顾问..."
});
fs.writeFileSync(zhFile, JSON.stringify(zhData, null, 2));

const enFile = './src/i18n/locales/en/kb.json';
const enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));
Object.assign(enData, {
  "basicSettings": "Basic Settings",
  "permissionsSettings": "Permissions Management",
  "modelSettings": "Model Settings",
  "basicSettingsDesc": "Modify name, appearance, icon, and KB scope.",
  "permissionsSettingsDesc": "Access Permissions & External Sharing",
  "permissionsSettingsDesc2": "Set collaborator duties and public access links.",
  "modelSettingsDesc": "LLM Agent Console",
  "modelSettingsDesc2": "Set AI inference engine parameters and system prompts.",
  "kbSpace": "KB Space",
  "kbRename": "Rename Knowledge Base",
  "kbRenamePlaceholder": "e.g., Product Architecture Specs...",
  "iconAvatarSelection": "Select Icon or Avatar",
  "recommendedSize": "Supports drag & drop. Recommended 512x512px, JPG/PNG.",
  "admin": "Admin",
  "editor": "Editor",
  "viewer": "Viewer",
  "collaborators": "Internal Collaborators",
  "addCollaborator": "Add collaborator email to maintain this KB",
  "emailPlaceholder": "Enter email (e.g., name@company.com)",
  "add": "Add",
  "owner": "Owner",
  "removeMember": "Remove Member",
  "cloudProvider": "Cloud AI Provider",
  "llmModel": "Linked LLM Engine",
  "temperature": "Temperature",
  "temperatureDesc": "Lower values output more deterministic facts; higher values yield creative diverse ideas.",
  "maxTokens": "Max Output Tokens",
  "maxTokensDesc": "Limit the maximum tokens generated by the engine.",
  "systemPrompt": "System Prompt & Persona",
  "systemPromptPlaceholder": "E.g., You are a financial advisor..."
});
fs.writeFileSync(enFile, JSON.stringify(enData, null, 2));

let file = './packages/sdkwork-knowledgebase-pc-knowledgebase/src/KnowledgeBaseSettingsModal.tsx';
let content = fs.readFileSync(file, 'utf8');

if (!content.includes('useTranslation')) {
    content = content.replace("import React, { useState, useRef } from 'react';", "import React, { useState, useRef } from 'react';\nimport { useTranslation } from 'react-i18next';");
}
// Inject t hook
if (!content.includes('const { t } = useTranslation([')) {
    content = content.replace("export function KnowledgeBaseSettingsModal({ kb, onClose, onSave }: KnowledgeBaseSettingsModalProps) {", "export function KnowledgeBaseSettingsModal({ kb, onClose, onSave }: KnowledgeBaseSettingsModalProps) {\n  const { t } = useTranslation(['kb', 'common']);");
}

// Basic hardcoded replacements using regex
content = content.replace(/'基础设置'/g, "t('basicSettings')");
content = content.replace(/'权限管理'/g, "t('permissionsSettings')");
content = content.replace(/'智脑模型设置'/g, "t('modelSettings')");
content = content.replace(/基础配置/g, "{t('basicSettings')}");
content = content.replace(/访问权限 & 外部共享设置/g, "{t('permissionsSettingsDesc')}");
content = content.replace(/大语言模型智能体控制台/g, "{t('modelSettingsDesc')}");
content = content.replace(/修改基本名称、外观、图标、知识库的分类范围。/g, "{t('basicSettingsDesc')}");
content = content.replace(/设置知识库组织成员协作职责，管理Public公开链路访问规则。/g, "{t('permissionsSettingsDesc2')}");
content = content.replace(/设置该知识库关联的 AI 理解驱动引擎参数及上下文智能指示。/g, "{t('modelSettingsDesc2')}");
content = content.replace(/知识库空间/g, "{t('kbSpace')}");
content = content.replace(/>知识库重命名</g, ">{t('kbRename')}<");
content = content.replace(/"例如：产品产品体验规格书..."/g, "t('kbRenamePlaceholder')");
content = content.replace(/>挑选图标或上传头像</g, ">{t('iconAvatarSelection')}<");
content = content.replace(/建议 512x512px，JPG\/PNG。/g, "{t('recommendedSize')}");
content = content.replace(/>内部协作成员</g, ">{t('collaborators')}<");
content = content.replace(/添加协作者邮箱，共同维护此知识库/g, "{t('addCollaborator')}");
content = content.replace(/"输入团队成员邮箱 \(如: name@company\.com\)"/g, "t('emailPlaceholder')");
content = content.replace(/管理员 \(Admin\)/g, "{t('admin')}");
content = content.replace(/编辑者 \(Editor\)/g, "{t('editor')}");
content = content.replace(/只读游客 \(Viewer\)/g, "{t('viewer')}");
content = content.replace(/>云算力主要提供商 \(AI Provider\)</g, ">{t('cloudProvider')}<");
content = content.replace(/>关联 LLM 大语言模型执行器</g, ">{t('llmModel')}<");
content = content.replace(/>创意随机温度 \(Temperature\)</g, ">{t('temperature')}<");
content = content.replace(/较低的数值产生更加确定性、准确的事实性回复；较高的数值会获得多样性、极具创意的扩散性回答，适合头脑风暴。/g, "{t('temperatureDesc')}");
content = content.replace(/>输出单词上限 \(Max Output Tokens\)</g, ">{t('maxTokens')}<");
content = content.replace(/配置生成引擎单词Token上限，约束大规模文本截断。/g, "{t('maxTokensDesc')}");
content = content.replace(/>设定专属系统提示词身份 \(System Prompt\)</g, ">{t('systemPrompt')}<");
content = content.replace(/输入身份预设，比如：你现在是金融顾问.../g, "t('systemPromptPlaceholder')");
content = content.replace(/>添加</g, ">{t('add')}<");
content = content.replace(/>保留修改并更新知识库</g, ">{t('saveConfig')}<");

fs.writeFileSync(file, content);
