const fs = require('fs');
const zhFile = './src/i18n/locales/zh/editor.json';
const zhData = JSON.parse(fs.readFileSync(zhFile, 'utf8'));
Object.assign(zhData, {
  "oaGroups": ["科技数码", "生活美食", "企业矩阵", "个人日常", "未分组"],
  "widgetQuotaTemplate": "￥50 专属代金券",
  "widgetMerchantTemplate": "AI智能基地",
  "widgetConditionTemplate": "满200元可用",
  "widgetQuestionTemplate": "如何看待未来 AGI 人工智能的发展？",
  "widgetAnswerTemplate": "通用人工智能 AGI 将会在各行业演进，通过更强大的多模态技术重塑世界生产力。",
  "widgetOptionsTemplate": ["非常看好，全面普及", "谨慎看待，发展漫长", "纯属概念，无法落地"],
  "aiGenSteps": [
    "分析文章主题与关键词...",
    "提取核心语义中...",
    "规划黄金分割视觉焦点...",
    "匹配高级专属色彩调色板...",
    "进行多维细节纹理渲染..."
  ],
  "widgetTitleLink": "访问我们的全栈代码官方星球",
  "widgetQuota2": "￥100 元超级全功能测试礼品卡",
  "widgetMerchant2": "SDKWork 专家智库",
  "widgetCondition2": "文章读者专享 · 无门槛全站通用",
  "widgetVoteTitle": "你认为未来5年内 AI 是否会重塑传统的公众号写作市场？",
  "widgetVoteOptions": ["完全会，内容生产迎来降本增效革命", "不可能，人文温度是AI无法替代的", "看具体垂类，有喜有忧"],
  "widgetSearchTitle": "微信官方搜索直达",
  "widgetLocationTitle": "SDKWork 科技与设计联合共创中心",
  "widgetLocationSubtitle": "深圳市科技南路 12 号高新技术产业园区",
  "widgetChannelTitle": "知识共享平台 · 超级开发者专访",
  "widgetQaQuestion": "如何才能制作出一期高含金量 and 全网高转化率的微信爆款排版？",
  "widgetQaAnswer": "最核心的是内容价值、结构对齐与视觉留白。使用我们的智能排版工具，可以一瞬间生成大师级比例排版而不需要手动摆放元素。",
  "widgetCardTitle": "SDKWork 知识智能",
  "widgetCardSubtitle": "专注于 AI 大模型、独立开发技术、全栈框架以及数字化工作流实战分享。",
  "widgetGiftsTitle": "送作者一杯温暖的生椰拿铁 ☕",
  "widgetPlaceholder": "【{{toolName}}】组件占位标志",
  "driveAuthor": "企业智能云盘",
  "driveAbstract": "来自网盘共享文件「{{title}}」",
  "driveHolderTitle": "从网盘导入的附件专区",
  "driveHolderAuthor": "企业云端硬盘",
  "driveHolderAbstract": "本文章包含从企业云硬盘一键转换并导入的不兼容特殊资源卡片",
  "rewriteSuccess": "一键AI重写完成！",
  "rewriteError": "AI重写任务异常",
  "toolImage": "图片",
  "toolVideo": "视频",
  "toolAudio": "音频",
  "toolLink": "超链接",
  "toolMiniprogram": "小程序",
  "toolCoupons": "卡券",
  "toolTemplates": "模板",
  "toolVote": "投票",
  "toolSearch": "搜索",
  "toolLocation": "地理位置",
  "toolChannel": "视频号",
  "toolQa": "问答",
  "toolAd": "收入变现",
  "toolCard": "账号名片",
  "toolGifts": "礼物",
  "saveSuccess": "保存成功"
});
fs.writeFileSync(zhFile, JSON.stringify(zhData, null, 2));

const enFile = './src/i18n/locales/en/editor.json';
const enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));
Object.assign(enData, {
  "oaGroups": ["Tech & Gadgets", "Food & Lifestyle", "Corporate", "Personal", "Ungrouped"],
  "widgetQuotaTemplate": "￥50 Exclusive Voucher",
  "widgetMerchantTemplate": "AI Intelligence Base",
  "widgetConditionTemplate": "Available for orders over ￥200",
  "widgetQuestionTemplate": "How do you view the future development of AGI?",
  "widgetAnswerTemplate": "AGI will evolve across industries, reshaping global productivity with powerful multimodal tech.",
  "widgetOptionsTemplate": ["Highly optimistic, widespread adoption", "Cautious, long road ahead", "Just a concept, cannot be realized"],
  "aiGenSteps": [
    "Analyzing theme and keywords...",
    "Extracting core semantics...",
    "Planning golden ratio focal points...",
    "Matching premium color palettes...",
    "Rendering multidimensional textures..."
  ],
  "widgetTitleLink": "Visit our Full-Stack Official Planet",
  "widgetQuota2": "￥100 Super Tester Gift Card",
  "widgetMerchant2": "SDKWork Expert Think Tank",
  "widgetCondition2": "Exclusive for readers · Universal without threshold",
  "widgetVoteTitle": "Will AI reshape the traditional WeChat writing market in the next 5 years?",
  "widgetVoteOptions": ["Absolutely, a revolution in efficiency", "Impossible, human warmth is irreplaceable", "Depends on the niche, mixed results"],
  "widgetSearchTitle": "WeChat Official Search Direct",
  "widgetLocationTitle": "SDKWork Tech & Design Co-creation Center",
  "widgetLocationSubtitle": "No. 12 Keji South Road, High-tech Industrial Park, Shenzhen",
  "widgetChannelTitle": "Knowledge Sharing Platform · Super Developer Interview",
  "widgetQaQuestion": "How to create a high-quality WeChat article with high conversion?",
  "widgetQaAnswer": "The core is content value, structural alignment, and white space. Using our smart tool, you can instantly generate master-level layouts.",
  "widgetCardTitle": "SDKWork Knowledge Intelligence",
  "widgetCardSubtitle": "Focusing on AI LLMs, indie hacking, full-stack frameworks, and digital workflows.",
  "widgetGiftsTitle": "Buy the author a warm iced coconut latte ☕",
  "widgetPlaceholder": "[{{toolName}}] Component Placeholder",
  "driveAuthor": "Enterprise Smart Drive",
  "driveAbstract": "From shared drive file '{{title}}'",
  "driveHolderTitle": "Attachment Zone from Cloud Drive",
  "driveHolderAuthor": "Enterprise Cloud Drive",
  "driveHolderAbstract": "This article contains incompatible special resource cards imported from the drive",
  "rewriteSuccess": "1-Click AI Rewrite Finished!",
  "rewriteError": "AI Rewrite Error",
  "toolImage": "Image",
  "toolVideo": "Video",
  "toolAudio": "Audio",
  "toolLink": "Hyperlink",
  "toolMiniprogram": "Mini Program",
  "toolCoupons": "Coupons",
  "toolTemplates": "Templates",
  "toolVote": "Vote",
  "toolSearch": "Search",
  "toolLocation": "Location",
  "toolChannel": "Channel",
  "toolQa": "Q&A",
  "toolAd": "Revenue Ad",
  "toolCard": "Account Card",
  "toolGifts": "Gifts",
  "saveSuccess": "Saved Successfully"
});
fs.writeFileSync(enFile, JSON.stringify(enData, null, 2));
