const fs = require('fs');

const zhFile = './src/i18n/locales/zh/kb.json';
const zhData = JSON.parse(fs.readFileSync(zhFile, 'utf8'));

Object.assign(zhData, {
  "blankKb": "空白知识库",
  "importFromGit": "从 Git 导入",
  "gitRepoUrl": "Git 仓库地址",
  "branch": "分支",
  "suggestedSize": "建议尺寸 200x200px，支持 jpg、png 格式",
  "teamKbDesc": "团队成员协作共享",
  "personalKbDesc": "仅对自己可见",
  "sharedKbDesc": "公开或订阅的多人共享知识库",
  "importAndCreate": "导入并新建",
  "importing": "导入中...",
  "moveTitle": "移动：",
  "copyTitle": "复制：",
  "move": "移动至",
  "copy": "复制至",
  "targetLocation": "请选择目标位置",
  "confirmMove": "确定移动",
  "confirmCopy": "确定复制",
  "currentTarget": "当前选中的目标: ",
  "publicLink": "公开链接",
  "teamVisibility": "团队成员可见性",
  "publicLinkDesc": "允许外部人员通过链接访问",
  "teamVisibilityDesc": "控制工作空间内的基础权限",
  "closedPrivate": "关闭 (私有)",
  "publicVisible": "公开可见",
  "publicEdit": "公开编辑",
  "allEditor": "所有成员 (可编辑)",
  "allViewer": "所有成员 (仅查看)",
  "specific": "仅指定成员",
  "memberPermissions": "成员权限设置",
  "setCollaboratorPermissions": "设置 {{title}} 的协作者权限",
  "publicLinkConfig": "公开链接访问控制",
  "deployToWebsite": "部署为独立网站",
  "deployToWebsiteDesc": "将当前知识库发布为对客友好、支持全文检索的多端自适应网站",
  "siteName": "网站名称",
  "siteNamePlaceholder": "公开显示的名称...",
  "themeColor": "主题配色",
  "domainConfig": "域名配置",
  "systemDomain": "系统分配域名",
  "deployStart": "立即部署上线",
  "saveConfig": "保存配置修改",
  "close": "关闭",
  "customDomain": "自定义域名 (企业版/旗舰版专属)",
  "deploying": "部署中",
  "deployed": "已部署",
  "offlineSite": "下线网站",
  "editableSite": "可于独立后台重新定制",
  "viewSite": "访问网站",
  "versionHistory": "版本历史",
  "historyOf": "{{title}} 的历史记录",
  "currentVersion": "当前版本",
  "initialVersion": "初始版本",
  "today": "今天",
  "importNotes": "导入备忘录",
  "importNotesDesc": "选择并同步草稿箱内容",
  "checkNotes": "勾选即将导入的备忘录内容：",
  "importingNotesTip": "导入后，备忘录内容将被转换为可编辑的知识库文档，并在本地安全存储。",
  "importCount": "导入 {{count}} 篇备忘录",
  "importFromPersonal": "从个人知识库导入",
  "importFromPersonalDesc": "一键多选导入您其它的个人知识库文档到当前团队空间",
  "personalKbList": "个人知识库列表",
  "noPersonalKb": "暂无个人知识库",
  "searchInKb": "搜索 \"{{kbName}}\" 内的文档...",
  "loadingDocs": "正在加载文档列表...",
  "noImportableDocs": "此库内无可导入文件",
  "noImportableDocsDesc": "您可以通过左侧切换其它的个人库，或在此库中新增文档",
  "selectAllPage": "全选当前页文档 ({{count}})",
  "editorPrefix": "编辑人：",
  "selectedPersonalDocs": "已选择 {{count}} 篇个人文档",
  "importSelected": "导入选中内容 ({{count}})",
  "importChatFile": "导入聊天文件",
  "chatFileDesc": "从对话记录中快速提取并归档有价值的文档",
  "fromWechatGroup": "微信群聊同步",
  "fromMcpConsole": "MCP终端输出",
  "selectedChatFiles": "已选择 {{count}} 份文件",
  "importSelectedFiles": "导入选中文件 ({{count}})",
  "selectTargetKb": "选择导入目标知识库",
  "targetFolder": "目标文件夹 (可选)",
  "defaultRoot": "默认根目录",
  "myEnterpriseDrive": "我的企业云盘",
  "driveDescription": "浏览、管理并导入云端文件与资料",
  "uploadToDrive": "上传文件",
  "syncUpdate": "同步更新",
  "driveUsage": "云盘用量: ",
  "folderEmpty": "当前文件夹为空"
});
fs.writeFileSync(zhFile, JSON.stringify(zhData, null, 2));

const enFile = './src/i18n/locales/en/kb.json';
const enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));

Object.assign(enData, {
  "blankKb": "Blank Knowledge Base",
  "importFromGit": "Import from Git",
  "gitRepoUrl": "Git Repository URL",
  "branch": "Branch",
  "suggestedSize": "Suggested size 200x200px, supports jpg, png formats",
  "teamKbDesc": "Collaborative sharing for team members",
  "personalKbDesc": "Visible only to you",
  "sharedKbDesc": "Public or subscribed multi-user shared knowledge base",
  "importAndCreate": "Import and Create",
  "importing": "Importing...",
  "moveTitle": "Move: ",
  "copyTitle": "Copy: ",
  "move": "Move to",
  "copy": "Copy to",
  "targetLocation": "Please select a target location",
  "confirmMove": "Confirm Move",
  "confirmCopy": "Confirm Copy",
  "currentTarget": "Current selected target: ",
  "publicLink": "Public Link",
  "teamVisibility": "Team Visibility",
  "publicLinkDesc": "Allow external access via link",
  "teamVisibilityDesc": "Control basic permissions within workspace",
  "closedPrivate": "Closed (Private)",
  "publicVisible": "Public Visible",
  "publicEdit": "Public Editable",
  "allEditor": "All members (Editor)",
  "allViewer": "All members (Viewer)",
  "specific": "Selected members only",
  "memberPermissions": "Member Permissions",
  "setCollaboratorPermissions": "Set collaborator permissions for {{title}}",
  "publicLinkConfig": "Public Link Access Control",
  "deployToWebsite": "Deploy as Website",
  "deployToWebsiteDesc": "Publish the current knowledge base as a customer-friendly, adaptive website with full-text search",
  "siteName": "Website Name",
  "siteNamePlaceholder": "Publicly displayed name...",
  "themeColor": "Theme Color",
  "domainConfig": "Domain Configuration",
  "systemDomain": "System Assigned Domain",
  "deployStart": "Deploy Now",
  "saveConfig": "Save Configuration",
  "close": "Close",
  "customDomain": "Custom Domain (Enterprise Exclusive)",
  "deploying": "Deploying",
  "deployed": "Deployed",
  "offlineSite": "Take Offline",
  "editableSite": "Customizable in separate dashboard",
  "viewSite": "Visit Website",
  "versionHistory": "Version History",
  "historyOf": "History of {{title}}",
  "currentVersion": "Current Version",
  "initialVersion": "Initial Version",
  "today": "Today",
  "importNotes": "Import Notes",
  "importNotesDesc": "Select and sync drafts",
  "checkNotes": "Select notes to import:",
  "importingNotesTip": "After importing, notes will be converted to editable docs and stored securely.",
  "importCount": "Import {{count}} Notes",
  "importFromPersonal": "Import from Personal KB",
  "importFromPersonalDesc": "Batch import docs from your personal KB to current team space",
  "personalKbList": "Personal KB List",
  "noPersonalKb": "No personal KB",
  "searchInKb": "Search docs in \"{{kbName}}\"...",
  "loadingDocs": "Loading document list...",
  "noImportableDocs": "No importable files in this KB",
  "noImportableDocsDesc": "You can select another personal KB from the left sidebar, or add new docs here.",
  "selectAllPage": "Select all on this page ({{count}})",
  "editorPrefix": "Editor: ",
  "selectedPersonalDocs": "Selected {{count}} personal docs",
  "importSelected": "Import Selected ({{count}})",
  "importChatFile": "Import Chat Files",
  "chatFileDesc": "Extract and archive valuable documents from chat history",
  "fromWechatGroup": "WeChat Group Sync",
  "fromMcpConsole": "MCP Console Output",
  "selectedChatFiles": "Selected {{count}} files",
  "importSelectedFiles": "Import Selected Files ({{count}})",
  "selectTargetKb": "Select Target Knowledge Base",
  "targetFolder": "Target Folder (Optional)",
  "defaultRoot": "Default Root Directory",
  "myEnterpriseDrive": "Enterprise Drive",
  "driveDescription": "Browse, manage, and import cloud files",
  "uploadToDrive": "Upload File",
  "syncUpdate": "Sync Update",
  "driveUsage": "Drive Usage: ",
  "folderEmpty": "Folder is empty"
});
fs.writeFileSync(enFile, JSON.stringify(enData, null, 2));
