$ErrorActionPreference = "Stop"

function Invoke-Checked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
    }
}

Invoke-Checked powershell -ExecutionPolicy Bypass -File tools/verify_sdkwork_structure.ps1

$knowledgebaseDesignPath = "docs/superpowers/specs/2026-06-01-knowledgebase-backend-design.md"
$knowledgebaseDesign = Get-Content -Raw $knowledgebaseDesignPath

$canonicalSdkGeneratorRoot = "..\sdkwork-sdk-generator"
$canonicalSdkGeneratorCli = "..\sdkwork-sdk-generator\bin\sdkgen.js"
$staleSdkGeneratorRoot = "..\..\sdkwork-sdk-generator"

if (!$knowledgebaseDesign.Contains($canonicalSdkGeneratorRoot) -or !$knowledgebaseDesign.Contains($canonicalSdkGeneratorCli)) {
    throw "$knowledgebaseDesignPath must document the canonical sdkwork-sdk-generator path and CLI entrypoint"
}

if ($knowledgebaseDesign.Contains($staleSdkGeneratorRoot)) {
    throw "$knowledgebaseDesignPath still references the old sdkwork-sdk-generator path: $staleSdkGeneratorRoot"
}

$requiredSdkStandardSnippets = @(
    "All SDKWork Knowledgebase HTTP SDKs MUST be generated by the canonical SDKWork generator",
    "--standard-profile sdkwork-v3",
    "--fixed-sdk-version 0.1.0",
    "sdkwork-sdk.json",
    ".sdkwork/sdkwork-generator-manifest.json",
    ".sdkwork/sdkwork-generator-changes.json",
    ".sdkwork/sdkwork-generator-report.json",
    "custom/",
    "node_modules/",
    "dist/",
    "package-lock.json"
)

foreach ($snippet in $requiredSdkStandardSnippets) {
    if (!$knowledgebaseDesign.Contains($snippet)) {
        throw "$knowledgebaseDesignPath must document SDK generation standard snippet: $snippet"
    }
}

$forbiddenSdkFamilyDirectories = @(
    "sdks/sdkwork-router-knowledgebase-app-api",
    "sdks/sdkwork-router-knowledgebase-backend-api"
)

foreach ($directory in $forbiddenSdkFamilyDirectories) {
    if (Test-Path $directory) {
        throw "API authority directory must not be a top-level SDK family directory: $directory"
    }
}

$requiredOpenApiSpecs = @(
    "sdks/sdkwork-knowledgebase-app-sdk/openapi/knowledgebase-app-api.openapi.json",
    "sdks/sdkwork-knowledgebase-backend-sdk/openapi/knowledgebase-backend-api.openapi.json",
    "sdks/sdkwork-knowledgebase-sdk/openapi/knowledgebase-open-api.openapi.json"
)

foreach ($specPath in $requiredOpenApiSpecs) {
    if (!(Test-Path $specPath)) {
        throw "Missing SDK family OpenAPI authority file: $specPath"
    }
}

$requiredGeneratedSdkRoots = @(
    "sdks/sdkwork-knowledgebase-app-sdk/sdkwork-knowledgebase-app-sdk-typescript/generated/server-openapi",
    "sdks/sdkwork-knowledgebase-backend-sdk/sdkwork-knowledgebase-backend-sdk-typescript/generated/server-openapi",
    "sdks/sdkwork-knowledgebase-sdk/sdkwork-knowledgebase-sdk-typescript/generated/server-openapi"
)

$requiredGeneratedSdkFiles = @(
    "sdkwork-sdk.json",
    "package.json",
    "tsconfig.json",
    "bin/publish-core.mjs",
    ".sdkwork/sdkwork-generator-manifest.json",
    ".sdkwork/sdkwork-generator-changes.json",
    ".sdkwork/sdkwork-generator-report.json"
)

foreach ($sdkRoot in $requiredGeneratedSdkRoots) {
    if (!(Test-Path $sdkRoot)) {
        throw "Missing generated SDK output root: $sdkRoot"
    }

    foreach ($requiredFile in $requiredGeneratedSdkFiles) {
        $requiredPath = Join-Path $sdkRoot $requiredFile
        if (!(Test-Path $requiredPath)) {
            throw "Missing generated SDK control/source file: $requiredPath"
        }
    }

    foreach ($requiredDirectory in @("src", "custom")) {
        $requiredPath = Join-Path $sdkRoot $requiredDirectory
        if (!(Test-Path $requiredPath -PathType Container)) {
            throw "Missing generated SDK directory: $requiredPath"
        }
    }

    $manifest = Get-Content -Raw (Join-Path $sdkRoot ".sdkwork/sdkwork-generator-manifest.json") | ConvertFrom-Json
    if (!$manifest.generatedFiles -or $manifest.generatedFiles.Count -eq 0) {
        throw "Generated SDK manifest has no generatedFiles entries: $sdkRoot"
    }

    foreach ($entry in $manifest.generatedFiles) {
        $generatedPath = [string]$entry.path
        if (
            $generatedPath.StartsWith("dist/") `
            -or $generatedPath.StartsWith("node_modules/") `
            -or $generatedPath -eq "package-lock.json"
        ) {
            throw "Generated SDK manifest must not include local build artifact: $sdkRoot/$generatedPath"
        }
    }
}

Invoke-Checked node tools/patch-route-manifest-extensions.mjs
Invoke-Checked node tools/patch-knowledgebase-app-api-extensions.mjs
Invoke-Checked node tools/sync-route-manifest-json.mjs
Invoke-Checked node tools/sync-context-binding-openapi.mjs
Invoke-Checked node tools/sync-upload-session-openapi.mjs
Invoke-Checked node tools/sync-openapi-operation-metadata.mjs
Invoke-Checked node tools/apply-knowledgebase-openapi-auth-mode.mjs
Invoke-Checked node tools/apply-knowledgebase-openapi-permissions.mjs
Invoke-Checked node tools/materialize-apis-authority.mjs
Invoke-Checked node tools/materialize-apis-authority.mjs --check
Invoke-Checked node sdks/standardize-knowledgebase-sdk-family.mjs --check
Invoke-Checked node sdks/test/verify-sdk-ownership-boundaries.test.mjs

$gitignore = Get-Content -Raw ".gitignore"
foreach ($ignoredArtifact in @(
    "sdks/**/generated/server-openapi/node_modules/",
    "sdks/**/generated/server-openapi/dist/",
    "sdks/**/generated/server-openapi/package-lock.json"
)) {
    if (!$gitignore.Contains($ignoredArtifact)) {
        throw ".gitignore must ignore generated SDK local build artifact: $ignoredArtifact"
    }
}

$generatedSdkBuildArtifacts = @()
foreach ($sdkRoot in $requiredGeneratedSdkRoots) {
    foreach ($artifactName in @("node_modules", "dist", "package-lock.json")) {
        $artifactPath = Join-Path $sdkRoot $artifactName
        if (Test-Path $artifactPath) {
            if ($artifactName -eq "node_modules") {
                Remove-Item -Recurse -Force $artifactPath
                continue
            }
            $generatedSdkBuildArtifacts += $artifactPath
        }
    }
}

if ($generatedSdkBuildArtifacts.Count -gt 0) {
    throw "Generated SDK local build artifacts must be removed before verification completes: $($generatedSdkBuildArtifacts -join ', ')"
}

$productionSourceRoots = @(
    "crates"
)

$drivePhysicalSqlPatterns = @(
    "FROM drive_",
    "JOIN drive_",
    "INSERT INTO drive_",
    "UPDATE drive_",
    "DELETE FROM drive_",
    "FROM dr_",
    "JOIN dr_",
    "INSERT INTO dr_",
    "UPDATE dr_",
    "DELETE FROM dr_"
)

foreach ($root in $productionSourceRoots) {
    foreach ($path in Get-ChildItem -Path $root -Recurse -File -Include *.rs) {
        if ($path.FullName -match "\\tests\\") {
            continue
        }

        if ($path.FullName -match "\\sdkwork-knowledgebase-drive\\") {
            continue
        }

        $content = Get-Content -Raw $path.FullName
        foreach ($pattern in $drivePhysicalSqlPatterns) {
            if ($content.Contains($pattern)) {
                throw "Knowledgebase production code must not access sdkwork-drive physical tables in $($path.FullName): $pattern"
            }
        }

        if (
            $content.Contains("sdkwork_drive_workspace_service::infrastructure") `
            -or $content.Contains("SqlDriveWorkspaceStore")
        ) {
            throw "Knowledgebase production code must call sdkwork-drive workspace service APIs instead of drive infrastructure internals: $($path.FullName)"
        }
    }
}

$packages = @(
    "sdkwork-knowledgebase-contract",
    "sdkwork-knowledgebase-agent-provider",
    "sdkwork-intelligence-knowledgebase-object-key-service",
    "sdkwork-knowledgebase-drive",
    "sdkwork-knowledgebase-memory",
    "sdkwork-router-knowledgebase-app-api",
    "sdkwork-router-knowledgebase-backend-api",
    "sdkwork-router-knowledgebase-open-api",
    "sdkwork-knowledgebase-worker",
    "sdkwork-intelligence-knowledgebase-service",
    "sdkwork-intelligence-knowledgebase-repository-sqlx",
    "sdkwork-knowledgebase-test-support"
)

foreach ($package in $packages) {
    Invoke-Checked cargo fmt -p $package --check
}

Invoke-Checked cargo test --workspace
Invoke-Checked node tools/check_okf_knowledge_bundle_standard.mjs
Invoke-Checked powershell -ExecutionPolicy Bypass -File tools/verify_openapi_operation_ids.ps1

$okfKnowledgeBundle = Get-Content -Raw docs/okf-knowledge-bundle.md
# Detect common mojibake/replacement characters without embedding them directly in this script.
if ($okfKnowledgeBundle.Contains([char]0x9225) -or $okfKnowledgeBundle.Contains([char]0x922B) -or $okfKnowledgeBundle.Contains([char]0xFFFD)) {
    throw "docs/okf-knowledge-bundle.md contains mojibake replacement text"
}

if (!$okfKnowledgeBundle.Contains("Database objects created by SDKWork Knowledgebase use the") -or !$okfKnowledgeBundle.Contains('`kb_` prefix')) {
    throw "docs/okf-knowledge-bundle.md must document the SDKWork Knowledgebase kb_ database object naming standard"
}

$databaseObjectSearchRoots = @(
    "crates/sdkwork-intelligence-knowledgebase-repository-sqlx/migrations",
    "crates/sdkwork-intelligence-knowledgebase-repository-sqlx/src",
    "crates/sdkwork-intelligence-knowledgebase-repository-sqlx/tests"
)

$oldDatabaseObjectPatterns = @(
    "CREATE TABLE IF NOT EXISTS knowledge_",
    "CREATE INDEX IF NOT EXISTS idx_knowledge_",
    "CREATE UNIQUE INDEX IF NOT EXISTS uk_knowledge_",
    "FROM knowledge_",
    "INSERT INTO knowledge_",
    "UPDATE knowledge_",
    "JOIN knowledge_",
    "pragma_table_info('knowledge_"
)

function Get-DefinedDatabaseObjects {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,
        [Parameter(Mandatory = $true)]
        [string]$Prefix
    )

    $objects = New-Object System.Collections.Generic.List[string]
    foreach ($line in $Content -split "`n") {
        $trimmed = $line.Trim()
        if ($trimmed.StartsWith($Prefix)) {
            $tail = $trimmed.Substring($Prefix.Length).Trim()
            $name = ($tail -split "\s+")[0].Trim('"')
            if (![string]::IsNullOrWhiteSpace($name)) {
                $objects.Add($name)
            }
        }
    }
    return $objects
}

foreach ($root in $databaseObjectSearchRoots) {
    foreach ($path in Get-ChildItem -Path $root -Recurse -File) {
        if ($path.Name -eq "migration_manifest.rs") {
            continue
        }

        $content = Get-Content -Raw $path.FullName
        foreach ($pattern in $oldDatabaseObjectPatterns) {
            if ($content.Contains($pattern)) {
                throw "Old knowledge_ database object usage remains in $($path.FullName): $pattern"
            }
        }

        foreach ($table in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE TABLE IF NOT EXISTS ") {
            if (!$table.StartsWith("kb_")) {
                throw "Knowledgebase database table must use kb_ prefix in $($path.FullName): $table"
            }
        }

        foreach ($index in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE INDEX IF NOT EXISTS ") {
            if (!$index.StartsWith("idx_kb_")) {
                throw "Knowledgebase database index must use idx_kb_ prefix in $($path.FullName): $index"
            }
        }

        foreach ($index in Get-DefinedDatabaseObjects -Content $content -Prefix "CREATE UNIQUE INDEX IF NOT EXISTS ") {
            if (!$index.StartsWith("uk_kb_")) {
                throw "Knowledgebase database unique index must use uk_kb_ prefix in $($path.FullName): $index"
            }
        }
    }
}

Write-Host "SDKWork Knowledgebase backend foundation verification passed."
